### PR TITLE
Roles: Fix Add-UiPathDefaultRoles

### PR DESCRIPTION
**Pull request by eugencutic**
## Description
- Add Logs.Create to Execute (from 19.4 Robot role)

Fixes [OR-13743](https://uipath.atlassian.net/browse/OR-13743)

### CODE REVIEW

**Review by alexandra-olteanu — APPROVED** [review]

**Review by cristipufu — CHANGES_REQUESTED** [review]
"Enable Process Execute" has all global permissions from 19.4 "Robot" role. The "Robot" role doesn't have the "Processes.View" permission. What am I missing? Please ignore the description in the issue and re-check all the permissions from the spec.

**Comment by alexandra-olteanu** [comment]
> "Enable Process Execute" has all global permissions from 19.4 "Robot" role. The "Robot" role doesn't have the "Processes.View" permission. What am I missing? Please ignore the description in the issue and re-check all the permissions from the spec.

I think you are right. Enable Process Execute should have only the global permissions. Processes.View is a folder permission.

**Review by bogdantma — APPROVED** [review]
Approving PR as Logs.Create has been added to the Execute Role.

**Comment by katumi691** [comment]
No permissions were set in the example 
"Add-UiPathRole -Name'Execute' -Permissions $RolesPermissions.Execute"

Permission was set after setting as follows
"Add-UiPathRole -Name'Execute' -Permissions $RolesPermissions.Execute.Split(",").Trim()"

Event confirmed on 19.10.15 on-premises, 20.6.9-release.50 cloud
UiPath.PowerShell 19.10.0.13
UiPath.PowerShell 20.2.0.29

Name             : Windows PowerShell ISE Host
Version          : 5.1.19041.1

I didn't know github and wrote it here. Is it okay?

**Comment by rusanu** [comment]
@katumi691 we updated the scripts with #120

**Pull request merged**
